// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbEXrt_0b5N30NV-YSpDU7PfNE0LKdSAc',
    appId: '1:808625853830:web:37d83375afa2b5b137c807',
    messagingSenderId: '808625853830',
    projectId: 'fbonur-testapp',
    authDomain: 'fbonur-testapp.firebaseapp.com',
    storageBucket: 'fbonur-testapp.appspot.com',
    measurementId: 'G-RD7WT987B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4NavEuvTiQu3VIipJUYyn4bNQJC2pjyQ',
    appId: '1:808625853830:android:0425d0f3b807244637c807',
    messagingSenderId: '808625853830',
    projectId: 'fbonur-testapp',
    storageBucket: 'fbonur-testapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDggBG8o1-BfO-u6RBdvqf5kqaksQDh7t0',
    appId: '1:808625853830:ios:e672ecd48edd1a7d37c807',
    messagingSenderId: '808625853830',
    projectId: 'fbonur-testapp',
    storageBucket: 'fbonur-testapp.appspot.com',
    iosClientId: '808625853830-fhaq95pppn5uuuqc401uj6mfospqheio.apps.googleusercontent.com',
    iosBundleId: 'com.tetrative.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDggBG8o1-BfO-u6RBdvqf5kqaksQDh7t0',
    appId: '1:808625853830:ios:976100e47e341add37c807',
    messagingSenderId: '808625853830',
    projectId: 'fbonur-testapp',
    storageBucket: 'fbonur-testapp.appspot.com',
    iosClientId: '808625853830-a57ltab4ssbk4i27259m2tjd57jgerio.apps.googleusercontent.com',
    iosBundleId: 'com.tetrative.testApp.RunnerTests',
  );
}
